export const AUTH_MUTATION = "AUTH_MUTATION";

export const LOGIN_MUTATION = "LOGIN_MUTATION";

export const LOGOUT_MUTATION = "LOGOUT_MUTATION";

export const FAVORITE_ARTICLE_MUTATION = "FAVORITE_ARTICLE_MUTATION";

export const FOLLOW_PROFILE_MUTATION = "FOLLOW_PROFILE_MUTATION";

export const GET_CURRENT_USER_QUERY = "GET_CURRENT_USER_QUERY";

export const GET_PROFILE_QUERY = "GET_PROFILE_QUERY";

export const GET_PROFILE_ARTICLES_QUERY = "GET_PROFILE_ARTICLES_QUERY";

export const GET_GLOBAL_ARTICLES_QUERY = "GET_GLOBAL_ARTICLES_QUERY";

export const GET_FEED_ARTICLES_QUERY = "GET_FEED_ARTICLES_QUERY";

export const GET_ARTICLE_QUERY = "GET_ARTICLE_QUERY";
